/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.duyag_program;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2-PC
 */
public class RPS extends javax.swing.JFrame {
      int ph1 = 5;
    int ph2 = 5;

    /**
     * Creates new form RPS
     */
    public RPS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Player 1");

        jLabel2.setText("player 2");

        jButton1.setText("VS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("1: Paper");

        jLabel4.setText("2: Rock");

        jLabel5.setText("3: Sccisor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(153, 153, 153))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(172, 172, 172))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:                                      
    int p1 = Integer.parseInt(txt1.getText());
    int p2 = Integer.parseInt(txt2.getText());



    // Check if game is already over
    if (ph1 <= 0 || ph2 <= 0) {
        return;
    }

    // Draw
    if (p1 == p2) {
        JOptionPane.showMessageDialog(rootPane,
                "DRAW!\n\nPlayer 1 Health: " + ph1 +
                "\nPlayer 2 Health: " + ph2,
                "RPS",
                JOptionPane.INFORMATION_MESSAGE);
    }

    // Paper vs Rock - Player 1 wins
    else if (p1 == 1 && p2 == 2) {
        ph2--;

        if (ph2 == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "PLAYER 1 WINS THE GAME!",
                    "GAME OVER",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Player 1 wins!\n\nPlayer 1 Health: " + ph1 +
                    "\nPlayer 2 Health: " + ph2,
                    "RPS",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Paper vs Scissor - Player 2 wins
    else if (p1 == 1 && p2 == 3) {
        ph1--;

        if (ph1 == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "PLAYER 2 WINS THE GAME!",
                    "GAME OVER",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Player 2 wins!\n\nPlayer 1 Health: " + ph1 +
                    "\nPlayer 2 Health: " + ph2,
                    "RPS",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Rock vs Paper - Player 2 wins
    else if (p1 == 2 && p2 == 1) {
        ph1--;

        if (ph1 == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "PLAYER 2 WINS THE GAME!",
                    "GAME OVER",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Player 2 wins!\n\nPlayer 1 Health: " + ph1 +
                    "\nPlayer 2 Health: " + ph2,
                    "RPS",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Rock vs Scissor - Player 1 wins
    else if (p1 == 2 && p2 == 3) {
        ph2--;

        if (ph2 == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "PLAYER 1 WINS THE GAME!",
                    "GAME OVER",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Player 1 wins!\n\nPlayer 1 Health: " + ph1 +
                    "\nPlayer 2 Health: " + ph2,
                    "RPS",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Scissor vs Paper - Player 1 wins
    else if (p1 == 3 && p2 == 1) {
        ph2--;

        if (ph2 == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "PLAYER 1 WINS THE GAME!",
                    "GAME OVER",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Player 1 wins!\n\nPlayer 1 Health: " + ph1 +
                    "\nPlayer 2 Health: " + ph2,
                    "RPS",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Scissor vs Rock - Player 2 wins
    else if (p1 == 3 && p2 == 2) {
        ph1--;

        if (ph1 == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "PLAYER 2 WINS THE GAME!",
                    "GAME OVER",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Player 2 wins!\n\nPlayer 1 Health: " + ph1 +
                    "\nPlayer 2 Health: " + ph2,
                    "RPS",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Invalid input
    else {
        JOptionPane.showMessageDialog(rootPane,
                "Invalid Input!\nPlease enter 1, 2, or 3.",
                "RPS",
                JOptionPane.INFORMATION_MESSAGE);
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
